#https://eeedotweb.com/blog/web/wordpress/docker-local-wordpress/
version: '3.3'
 
services:
   wordpress:
     build: wordpress/
     image: webint/wordpress:latest
     container_name: webint_wordpress
     depends_on:
       - db
     ports:
       - "3001:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
     volumes:
       - ./wordpress/wp-content:/var/www/html/wp-content
       - ./wordpress/files:/var/www/html/files
 
   db:
     image: mysql:5.7
     container_name: webint_mysql
     ports:
      - "4306:3306"
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
       
volumes:
    db_data: